apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: microservices
data:
  FLASK_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/microservices"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
