apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_DB: microservices
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres  # Change in production!
